name: trip_advisor
description: "Get advices from other travelers and share your own experiences. Also, you can find the best places to visit in the world by AI."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.4
  http: ^1.2.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  google_places_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
